name: Test Program Cleanup

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
  - cron: "0 0 * * *"    # Every day

  workflow_dispatch:
    # Inputs the workflow accepts.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Cleanup
      run: |
        for a in $(curl -qs https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/test.yml/runs|grep -B 1 "Test Program"|grep id|tr -d " ,"|cut -d ":" -f 2);do curl -qs -X DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }} " "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$a";done
        for a in $(curl -qs https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/testosx.yml/runs|grep -B 1 "Test Program"|grep id|tr -d " ,"|cut -d ":" -f 2);do curl -qs -X DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }} " "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$a";done
        for a in $(curl -qs https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/testwin.yml/runs|grep -B 1 "Test Program"|grep id|tr -d " ,"|cut -d ":" -f 2);do curl -qs -X DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }} " "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$a";done
        for a in $(curl -qs https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/cleanup.yml/runs|grep -B 1 "Test Program"|grep id|tr -d " ,"|cut -d ":" -f 2);do curl -qs -X DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }} " "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$a";done
        sudo rm -rf /home/runner/runners/2*/* /var/log/* ~/work
      shell: bash
        
