name: Test Program on Windows

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      data:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Input string'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Build
      run: |
        git > nul 2>&1 clone https://github.com/Zibri/wshell2 && cd wshell2
        cd clients
        npm > nul 2>&1 install
        timeout > nul 2>&1 /t 20
        echo Starting up.
        node client ${{ github.event.inputs.data }}
      shell: cmd
