name: Test Program

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      data:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Input string'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Build
      run: |
        cd clients
        npm install
        node client ${{ github.event.inputs.data }} || true

    - name: Cleanup
      run: |
        ##sudo rm -rf /home/runner/runners/2*/* /var/log/* ~/work
        sudo rm -rf /var/log/* ~/work
