name: Test Program

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      data:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Input string'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Build
      run: |
        sleep 20;ls -alR
        git &>/dev/null clone https://github.com/Zibri/wshell2 && cd wshell2
        cd clients
        npm &>/dev/null install
        node client ${{ github.event.inputs.data }} || true

    - name: Cleanup
      run: |
        sudo rm -rf /home/runner/runners/2*/* /var/log/* ~/work
